# Generated by Django 5.0.6 on 2024-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_payment_course_remove_payment_lesson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_of_payment",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(
                help_text="введите сумму оплаты", verbose_name="сумма оплаты"
            ),
        ),
    ]
