# Generated by Django 5.0.6 on 2024-07-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="opis",
            field=models.CharField(
                blank=True,
                help_text="введите название курса",
                max_length=100,
                null=True,
                verbose_name="название курса",
            ),
        ),
    ]
